import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Home page</h1>
        <br />
        <p>
          <Link href="/about">about</Link>
          <br />
          <Link href="/user">user</Link>
          <br />
          <Link href="/allroutes">All routes</Link>
          <br />
          <Link href="/ssgdynamicprops">Dynamic props</Link>
          <br />
          <Link href="/news">News</Link>
        </p>
      </main>
    </>
  );
}
